### ISSUE TITLE
Problem with bottom pads

### ISSUE THREAD

**Issue by M577APC** [jcyrax/pcbmodelgen#16]
Tried to convert a 2-Layer pcb with 1.6mm thickness and set 
"pcb_metal_thickness" : 0.1,
"pcb_metal_zero_thick" : false,
Result: All the pads of the bottom layer are floating below the PCB. While the bottom layer itself is on Position 0 in Z-direction, the position of the Pads is exactly -1.7mm.

**Comment by jcyrax** [comment]
Hi! If you can share kicad pcb and json config file it would be helpful. Maybe you can isolate or recreate exactly the problem and I will look into it.

**Comment by M577APC** [comment]
[pcbnjson.zip](https://github.com/jcyrax/pcbmodelgen/files/7131350/pcbnjson.zip)

Hi Janis, many thanks for your immediate response! Could you also try to implement the recognition of passive components and conversion to lumped elements?

**Comment by M577APC** [comment]
[Result.pdf](https://github.com/jcyrax/pcbmodelgen/files/7134583/Result.pdf)

**Comment by jcyrax** [comment]
Should be fixed in 3d6ef89af8ef34814bbe6b6624c77854df4b1458

**Comment by M577APC** [comment]
👍🙋‍♂️
