### ISSUE TITLE
Project clarifications

### ISSUE THREAD

**Issue by 0xCoto** [jcyrax/pcbmodelgen#17]
Hi there, this looks like a very interesting project! 🙂

Just wanted to clarify: is the main purpose of the work to automatically convert KiCAD PCBs to Octave models? My understanding is that this can already be done using the STL import offered by OpenEMS, by e.g. transforming a STEP model of the PCB into STLs for each object.

Or is the tricky part that this repository tackles the meshing itself? I've seen OpenEMS struggle with (manual) mesh generation a bit, so it'd be nice to hear that this project can help in that regard a bit.

Cheers,
Apostolos

**Comment by jcyrax** [comment]
I started this project because of my specific needs during one project. My main goal was to automatically generate mesh lines. I don't remember details and why I chose to write from scratch. It could be that currently there are more useful open tools for all of this.
