### ISSUE TITLE
Accept pr with clang-format?

### ISSUE THREAD

**Issue by matthuszagh** [jcyrax/pcbmodelgen#2]
Thanks for writing this program!

I'm making some modifications to support kicad 5. I personally use clang-format and was wondering if you'd be open to accepting a pr with formatting changes from a clang-format script. I'll try to make it as similar to the existing style as possible (e.g. 4 spaces indent, etc.). Additionally, are you interested in the kicad 5 pr's when I get those working?

**Comment by jcyrax** [comment]
> if you'd be open to accepting a pr with formatting changes from a clang-format script

Do you mean reformat all code base to be consistent using some clang-format style? I have no objections to that, if its about the same as current style, just add the style file in PR.

> Additionally, are you interested in the kicad 5 pr's when I get those working?

Yes, that would be very much appreciated. I currently have no plans and time to develop this any further.

**Comment by matthuszagh** [comment]
Here's the [pr](https://github.com/jcyrax/pcbmodelgen/pull/3). Let me know if you'd like anything adjusted.
