### ISSUE TITLE
Bad copper infills (kicad 7.0.0)

### ISSUE THREAD

**Issue by ThomHPL** [jcyrax/pcbmodelgen#20]
When using a pcb file from kicad v7.0.0, some copper infills are not generated correctly due to some points being stored as "NaN" in the files generated by pcbmodelgen.

I tracked down the issue to a float issue in the function Zone::getVectAngle. I have made a quick fix and will issue a pull request soon.

# Bad output
![bad](https://github.com/jcyrax/pcbmodelgen/assets/15064079/85b78f9d-51d5-4c83-befc-d6473d69314d)

# Good output
![good](https://github.com/jcyrax/pcbmodelgen/assets/15064079/03f54bed-6eac-4841-b727-41755ac276a8)

# Full kicad version info
Application: KiCad PCB Editor x64 on x64
Version: (7.0.0), release build
Libraries:
    wxWidgets 3.2.1
    FreeType 2.12.1
    HarfBuzz 5.0.1
    FontConfig 2.14.1
    libcurl/7.83.1-DEV Schannel zlib/1.2.13
Platform: Windows 11 (build 22621), 64-bit edition, 64 bit, Little endian, wxMSW
Build Info:
    Date: Feb 12 2023 01:35:19
    wxWidgets: 3.2.1 (wchar_t,wx containers)
    Boost: 1.80.0
    OCC: 7.6.2
    Curl: 7.83.1-DEV
    ngspice: 39
    Compiler: Visual C++ 1934 without C++ ABI
Build settings:
    KICAD_SPICE=ON

**Comment by leoheck** [comment]
Hi guys, is this issue resolved?

**Comment by ThomHPL** [comment]
Hi, my fix was merged and it works flawlessly for me. Let me know if you encounter issues.

**Comment by leoheck** [comment]
Sure, this issue can be closed then. If I have issues I can open a new issue.
