### ISSUE TITLE
[SOLVED] can pcbmodelgen recognize primitive non-rectangular boards (Egde.Cuts)?

### ISSUE THREAD

**Issue by rpelicia** [jcyrax/pcbmodelgen#23]
First of all, thanks for pcbmodelgen!
On Kicad v7.07, pcbmodelgen v0.2.0 correctly recognizes primitive rectangular boards (Egde.Cuts), but it doesn't recognize neither primitive circles nor polygons.

![image](https://github.com/jcyrax/pcbmodelgen/assets/94800810/45e70c89-f045-405b-9b35-e2ef99278bf6)
 Below, we see the three geometries on the KiCad file. But the rectangle is the only one that pcbmodelgen passes ahead to OpenEMS. Am I missing something obvious? The native recognition of circular boards would be very beneficial, as OpenEMS stands out among other solvers for being able to work with polar coordinates. Thanks!
  
![Screenshot from 2023-09-28 08-35-18](https://github.com/jcyrax/pcbmodelgen/assets/94800810/a86dcc1d-3b1d-4013-a1c7-76e1cb3ee784)
![Screenshot from 2023-09-28 08-38-06](https://github.com/jcyrax/pcbmodelgen/assets/94800810/ae9d5109-484a-47d7-ac67-c1582bcc673a)
 --------------------
**[SOLVED]** 
I found a simple solution for that. If you have a circular PCB in KiCad, first convert the primitive circle to a Polygon (Right click > Create from selection > Create Polygon from selection). Then convert the polygon to Lines (Right click > Create from selection > Create Lines from selection). Done. Now pcbmodelgen will recognize any Egde.Cuts.

**Comment by jcyrax** [comment]
Yes, if I remember correctly polygons for board edge is the way for complex forms.
