### ISSUE TITLE
Running it on Ubuntu 20.04

### ISSUE THREAD

**Issue by leoheck** [jcyrax/pcbmodelgen#6]
Hello, I am testing your tool with Ubuntu 20.04.

I managed to install it and all required dependencies.
Maybe I can document this if you are interested in that.

I also had to add 2 paths on the `.octaverc` so the tools could find the `OpenEMS` and `CSXCAD` files as you said in another issue.

Right now I am running this for the first time using the `test_pcb`

![image](https://user-images.githubusercontent.com/1277920/84728288-49086280-af67-11ea-9550-503e0495c26e.png)

I hope to be able to run this for my board.

**Comment by leoheck** [comment]
Also, I saw that this example was build using Kicad nightly build. It would be nice to port it to the `5.1.*` stable so more people could open it easily. But the fix is straightforward.

I just had to remove these red lines.
![image](https://user-images.githubusercontent.com/1277920/84728501-c338e700-af67-11ea-8c2c-a76fb96db301.png)

**Comment by jcyrax** [comment]
Yes, I agree. Need to update examples to new version.
